Api/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('api/ticket/create', views.addTicketApi, name='apicreateticket'),
    path('api/ticket/all', views.allTicketsAPi, name='apigetalltickets'),
    path('api/event/create', views.addEvent, name='apicreateevent'),
    path('api/event/all', views.allEventsAPi, name='apigetallevents'),
    path('api/category/create', views.addCategory, name='apicreatecategory'),
    ]
    

Tkmanger/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings  
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Tktapp.urls')),
    path('',include('Api.urls')),
                    
]
if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

Tktapp/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.index, name='home'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logoutUser, name='logout'),
    path('user/profile/', views.userProfile, name='userprofile'),
    path('user/editprofile/', views.editProfile, name='editprofile'),
    path('events/', views.event, name='eventlist'),
    path('events/detail/<pk>/', views.eventDetail, name='eventdeatail'),
    path('events/create/', views.eventCreate, name='eventcreate'),
    path('mytickets/image/<pk>/', views.tickeTotPdf, name='ticketpdf'),
    path('mytickets/', views.myTickets, name='mytickets'),
    # path('api-auth/', include('rest_framework.urls')),

]

Tktapp/models.py
import uuid
from distutils.command.upload import upload
from django.db import models
from .usermanager import UserManager
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth import get_user_model


class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)  # a admin user; non super-user
    admin = models.BooleanField(default=False)  # a superuser
    full_name = models.CharField(max_length=25, blank='true')
    phone_no = models.IntegerField(null=True, blank=True, unique=True)
    is_author = models.BooleanField(default=False)
    # notice the absence of a "Password field", that is built in.
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []  # Email & Password are required by default.
    objects = UserManager()

    def get_full_name(self):
        full_name = f'{self.first_name} {self.last_name}'
        return full_name

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.staff

    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin


user = get_user_model()


class Event(models.Model):
    uid = models.UUIDField(default=uuid.uuid4, editable=False,unique=True)
    user = models.ForeignKey(user, null=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    thumbnail = models.ImageField(null=True,blank=True, upload_to='images/')
    about = models.TextField()
    location = models.CharField(max_length=100)
    ticket_size = models.IntegerField()
    tickets_left = models.IntegerField(null=True,blank=True)
    start_date = models.DateField(auto_now_add=False, null=True)
    start_time = models.TimeField(null=True,blank=True,)
    end_time = models.TimeField(null=True,blank=True)
    end_date = models.DateField(null=True, blank=True)
    has_categories = models.BooleanField(default=False)
    value = models.IntegerField(null=True,blank=True)
    
    def has_categories(self):
        if self.has_categories is False:
            return self.value
        else:
            return self.has_categories
    

    def __str__(self):
        return self.title


class Categories(models.Model):
    event = models.ForeignKey(Event, null=True, on_delete=models.SET_NULL)
    category_name = models.CharField(max_length=25)
    value = models.IntegerField()


class Ticket(models.Model):
    User = models.ForeignKey(user, null=True, on_delete=models.SET_NULL)
    event = models.ForeignKey(Event, null=True, on_delete=models.SET_NULL)
    username = models.CharField(max_length=30 ,null=True ,blank=True)
    price = models.IntegerField()
    serial_no = models.CharField(max_length=20)
    ticket_type = models.CharField(max_length=20)
    saved = models.BooleanField(default=False, blank=True ,null=True)

Tktapp/forms.py
from dataclasses import fields
from django import forms
from django.forms import inlineformset_factory
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField,PasswordChangeForm
from .models import *

User = get_user_model()


class UserAdminCreationForm(forms.ModelForm):
    """
    A form for creating new users. Includes all the required
    fields, plus a repeated password.
    """
    password = forms.CharField(widget=forms.PasswordInput)
    password_2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email','full_name'] 

    def clean(self):
        '''
        Verify both passwords match.
        '''
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_2 = cleaned_data.get("password_2")
        if password is not None and password != password_2:
            self.add_error("password_2", "Your passwords must match")

        return cleaned_data

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field."""
   

    class Meta:
        model = User
        fields = '__all__'

    def clean_password(self):
        return self.initial["password"]

class EventForm(forms.ModelForm):
	class Meta:
		model = Event
		fields = '__all__'

class CategoryForm(forms.ModelForm):
	class Meta:
		model = Categories
		fields = '__all__'

class Ticketform(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = '__all__'


CategoryInlineFormset = inlineformset_factory(
    Event,
    Categories,
    form=CategoryForm,
    extra=5,
    # max_num=5,
    # fk_name=None,
    # fields=None, exclude=None, can_order=False,
    # can_delete=True, max_num=None, formfield_callback=None,
    # widgets=None, validate_max=False, localized_fields=None,
    # labels=None, help_texts=None, error_messages=None,
    # min_num=None, validate_min=False, field_classes=None
)

TicketInlineFormset = inlineformset_factory(
    Event,
    Ticket,
    form= Ticketform,
    extra=1,
    # max_num=5,
    # fk_name=None,
    # fields=None, exclude=None, can_order=False,
    # can_delete=True, max_num=None, formfield_callback=None,
    # widgets=None, validate_max=False, localized_fields=None,
    # labels=None, help_texts=None, error_messages=None,
    # min_num=None, validate_min=False, field_classes=None
)

class PasswordChangeCustomForm(PasswordChangeForm):
    pass

    

Tktapp/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from .models import *
from . forms import Ticketform, UserAdminCreationForm, EventForm, CategoryInlineFormset, UserAdminChangeForm, TicketInlineFormset, PasswordChangeCustomForm
from .filters import EventFilter
from django.views import generic
from django.contrib import messages
from django.contrib.auth import authenticate, login as lg, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .pdfrender import PdfRender
from django.utils import timezone


ticket_store = {'event': [], 'price': [], 'serial_no': [], 'ticket_type': []}


def index(request):

    event = Event.objects.all()
    myFilter = EventFilter(request.GET, queryset=event)
    events = myFilter.qs
    context = {'events': events,
               'myFilter': myFilter
               }
    return render(request, 'index.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        if request.method == 'POST':
            email = request.POST.get('email')
            password = request.POST.get('password')

            user = authenticate(request, email=email, password=password)

            if user is not None:
                lg(request, user)
                return redirect('home')
            else:
                messages.error(request, 'Username OR password is incorrect')

        context = {}
        return render(request, 'login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('home')


def register(request):
    context = {}
    form = UserAdminCreationForm
    context = {
        'form': form,
        'is_valid': True
    }
    if request.method == 'POST':
        form = UserAdminCreationForm(request.POST)
        if form.is_valid():
            print('good')
            form.save()
        else:
            messages.info(request, 'invalid registration details')
            print('error')
    return render(request, 'register.html', context)


def eventDetail(request, pk):

    event = Event.objects.get(uid=pk)
    event_categories = event.categories_set.all()

    context = {
        'formset': TicketInlineFormset(),
        'object': event,
        'categories': event_categories,

    }
    ticket_formset = TicketInlineFormset(request.POST)
    print(request.POST)
    if ticket_formset.is_valid():
        print(request.POST)
        ticket_formset.save()

    return render(request, "eventdetail.html", context)


def event(request):

    event = Event.objects.all()
    print(request.GET)
    myFilter = EventFilter(request.GET, queryset=event)
    events = myFilter.qs
    context = {'events': events,
               'myFilter': myFilter
               }
    return render(request, 'events.html', context)


@login_required(login_url='/login')
def eventCreate(request):
    form_class = EventForm
    template_name = 'eventcreate.html'
    context = {
        'user': request.user,
        'form': form_class
    }
    return render(request, 'eventcreate.html', context)


@login_required(login_url='/login')
def userProfile(request):

    _user = request.user
    event_count = Event.objects.filter(user=_user).count()
    ticket_count = Ticket.objects.filter(User=_user).count()
    checked_out = Ticket.objects.filter(saved=True).count()
    context = {
        'user': request.user,
        'event_count': event_count,
        'ticket_count': ticket_count,
        'checked_out': checked_out,
    }
    return render(request, 'userprofile.html', context)


@login_required
def editProfile(request):

    if request.method == 'POST':
        form = UserAdminChangeForm(request.POST, instance=request.user)
        pass_form = PasswordChangeCustomForm(request.POST)
        if form.is_valid() or pass_form.is_valid():
            pass_form.save()
            form.save()
        else:
            messages.info(request, 'invalid registration details')

    form = UserAdminChangeForm(instance=request.user)
    pass_form = PasswordChangeCustomForm(request.user)
    context = {'form': form, 'pass_form': pass_form}

    return render(request, 'editprofile.html', context)


@login_required
def myTickets(request):

    _user = request.user
    tickets = Ticket.objects.filter(User=_user)
    if request.method == 'POST':
        form = Ticketform(request.POST)
        print(request.POST['username'])

    context = {
        'user': request.user,
        'tickets': tickets,
    }
    return render(request, 'mytickets.html', context)


@login_required
def tickeTotPdf(request, pk):

    _user = request.user
    ticket = Ticket.objects.get(id=pk)

    today = timezone.now()
    params = {
        'today': today,
        'ticket': ticket,
        'request': request,

    }
    return render(request, 'ticket.html', params)

Tktapp/templates/editprofile.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Edit profile</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
<div class="container">
    <div class="main-body">
    
          <!-- Breadcrumb -->
          <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="index.html">Home</a></li>
              <li class="breadcrumb-item"><a href="javascript:void(0)">User</a></li>
              <li class="breadcrumb-item active" aria-current="page">User Profile</li>
            </ol>
          </nav>
          <!-- /Breadcrumb -->
    
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="{% static '/img/avatar.webp' %}" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{request.user.full_name}}</h4>

                      <p class="text-muted font-size-sm">{{request.user}}</p>

                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-header">Account Details</div>
                <div class="card-body">
                    <form method="POST">
                      {% csrf_token %}
                        <div class="mb-3">
                            <label class="small mb-1" for="inputUsername">{{form.full_name.label}}</label>
                            {{form.full_name}}
                        </div>
                        <!-- Form Row-->
                        <div class="row gx-3 mb-3">
                            <!-- Form Group (first name)-->
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputFirstName">{{form.phone_no.label}}</label>
                                {{form.phone_no}}
                            </div>
                            <!-- Form Group (last name)-->
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputLastName">Activate to Event creator</label><br>
                                {{form.is_author}}
                            </div>
                        </div>
                        <div class="mb-3">
                            <label class="small mb-1" for="inputEmailAddress">Email address</label>
                            {{form.email}}
                        </div>
                        <!-- Form Row-->
                        <!-- <div class="row gx-3 mb-3" >
            
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputPhone">old password</label>
                                {{pass_form.old_password}}
                            </div>
                     
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputBirthday">{{pass_form.new_password1.label}}</label>
                                {{pass_form.new_password1}}
                                <label class="small mb-1" for="inputBirthday">{{pass_form.new_password2.label}}</label>
                                {{pass_form.new_password2}}
                                
                                
                            </div> -->
                        </div>
                        <!-- Save changes button-->
                        <button class="btn btn-primary" type="submit">Save changes</button>
                    </form>
                </div>
    
                <div class="card mb-3">
                  <div class="card-header">Password</div>
                  <div class="card-body">
                      <form method="POST">
                        {% csrf_token %}
                          <div class="row gx-3 mb-3" >
              
                              <div class="col-md-6">
                                  <label class="small mb-1" for="inputPhone">old password</label>
                                  {{pass_form.old_password}}
                              </div>
                       
                              <div class="col-md-6">
                                  <label class="small mb-1" for="inputBirthday">{{pass_form.new_password1.label}}</label>
                                  {{pass_form.new_password1}}
                                  <label class="small mb-1" for="inputBirthday">{{pass_form.new_password2.label}}</label>
                                  {{pass_form.new_password2}}
                                  
                                  
                              </div>
                    
                          <button class="btn btn-primary" type="submit">Save changes</button>
                      </form>
                  </div>
                </div>
  

            </div>
          </div>
    </div>
        </div>
    </div>

<style type="text/css">
body{
    margin-top:20px;
    color: #1a202c;
    text-align: left;
    background-color: #e2e8f0;    
}
.main-body {
    padding: 15px;
}
.card {
    box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
}

.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0,0,0,.125);
    border-radius: .25rem;
}

.card-body {
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1rem;
}

.gutters-sm {
    margin-right: -8px;
    margin-left: -8px;
}

.gutters-sm>.col, .gutters-sm>[class*=col-] {
    padding-right: 8px;
    padding-left: 8px;
}
.mb-3, .my-3 {
    margin-bottom: 1rem!important;
}

.bg-gray-300 {
    background-color: #e2e8f0;
}
.h-100 {
    height: 100%!important;
}
.shadow-none {
    box-shadow: none!important;
}
.form-check-input {
    position: absolute;
    margin-top: 0.3rem;
    margin-left: 0; 
    padding-bottom: 5px;
}

</style>

<script type="text/javascript">


  $('input[type=text]').addClass('form-control');
  $('input[type=email]').addClass('form-control');
  $('input[type=number]').addClass('form-control');
  $('input[type=password]').addClass('form-control');
  $('input[type=checkbox]').addClass('form-check-input');
  $('#id_start_date').get(0).type = 'date';
  $('#id_end_date').get(0).type = 'date';
  </script>
</body>
</html>

Tktapp/templates/eventcreate.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>create event</title>

  <link rel="stylesheet" href="{% static 'css/linearicons.css' %}" />
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
  <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" />
  <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" />
  <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" />
  <link rel="stylesheet" href="{% static 'css/animate.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" />
  <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" />
  <link rel="stylesheet" href="{% static 'css/main.css' %}" />
  <link rel="stylesheet" href="{% static 'css/eventcreate.css' %}" />
  <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet" />
</head>

<body class="banner-area">
  <header id="header">
    <div class="container main-menu">
      <div class="row align-items-center justify-content-between d-flex">
        <div id="logo">
          <a href="index.html">TICKETY</a>
        </div>
        <nav id="nav-menu-container">
          <ul class="nav-menu">
            <li><a href="index.html">Home</a></li>
            <li><a href="/events">Events</a></li>
            <li><a href="/mytickets">My Tickets</a></li>
            {% if request.user.is_authenticated %}
            <li><a href="/logout">(logout)</a></li>
            {% else %}
            <li><a href="/login&register">login/sign up</a></li>
            {% endif %}
            <li class="menu-has-children">
              <a href="#">Create Events</a>
              <ul>
                <li><a href="/events/create">CREATE EVENT</a></li>
                <li><a href="blog-home.html">TUTORIAL</a></li>

              </ul>
            </li>
            <li><a href="user/profile">{{request.user}}</a></li>
          </ul>
        </nav>
        <!-- #nav-menu-container -->
      </div>
    </div><br>
  </header>
  <br>
  <section>
    <div class="create-form">
      <u>
        <h3>Event create form</h3>
      </u>
      <form method="POST" id="upload">
        {% csrf_token %}
        <div class="row">
          <div class="col-md-4">
            <label for="id_title" class="form-label">Title:</label>
            <input type="text" name="title" maxlength="100" required="" id="id_title" class="form-control" />
          </div>


          <div class="col-md-4">
            <label for="id_location" class="form-label">Location:</label>
            <input type="text" name="location" maxlength="100" required="" id="id_location" class="form-control" />
          </div>


          <div class="col-md-4">
            <label for="id_thumbnail" class="form-label">Event Poster:</label>
            <input type="file" name="thumbnail" accept="image/*" id="id_thumbnail" class="form-control" required />
          </div>

          <div class="col-md-4">
            <label for="id_ticket_size" class="form-label">Maximum Number of Tickets:</label>
            <input type="number" name="ticket_size" required id="id_ticket_size" class="form-control" />
          </div>
          <div class="col-md-4">
            <label for="id_about" class="form-label">About:</label>
            <textarea name="about" cols="40" rows="10" required="" id="id_about" class="form-control"
              style="height: 100px;"></textarea>
          </div>

          <div class="col-md-4">
            <label for="id_start_date" class="form-label">Start date:</label>
            <input type="date" name="start_date" id="id_start_date" class="form-control" required />
          </div>

          <div class="col-md-4">
            <label for="id_start_time" class="form-label">Start time:</label>
            <input type="time" name="start_time" id="id_start_time" class="form-control" required />
          </div>

          <div class="col-md-4">
            <label for="id_end_time" class="form-label">End time:</label>
            <input type="time" name="end_time" id="id_end_time" class="form-control" required />
          </div>

          <div class="col-md-4">
            <label for="id_end_date" class="form-label">End date:</label>
            <input type="date" name="end_date" id="id_end_date" class="form-control" required />
          </div>

          <div class="row col-md-12 categories-container" style="margin: 5px;
      ">
            <div class="form-group col-md-3 ">
              <label for="" class="form-label">Add a Ticket price</label><br>
              <button type="button" class="btn btn-primary" id="addCategory">Add Category</button>
            </div>
          </div>
          <div class="col-md-4">
            <label for="id_submit" class="form-label">click to Submit:</label><br>
            <button type="" class="submit-btn" id="id_submit">Create Event</button>
          </div>
        </div>
      </form>

      <div class="modal fade" id="categoryModal" tabindex="-1" role="dialog" aria-labelledby="categoryModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="categoryModalLabel">Add Category and Price</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="form-group">
                <label for="categoryName">Category Name:</label>
                <input type="text" class="form-control" id="categoryName">
              </div>
              <div class="form-group">
                <label for="categoryPrice">Category Price:</label>
                <input type="number" class="form-control" id="categoryPrice">
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary" id="saveCategory">Save</button>
            </div>
          </div>
        </div>
      </div>
      <div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="successModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                  <div id="successBadge" class="alert alert-success" role="alert">
                    <h4 class="alert-heading">Success!</h4>
                    <p>Your Event creaion was successful.</p>
                </div>
                </div>
            </div>
        </div>
    </div>
    
 
    
    
  </section>
  <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/easing.min.js' %}"></script>
  <script src="{% static 'js/hoverIntent.js' %}"></script>
  <script src="{% static 'js/superfish.min.js' %}"></script>
  <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/eventcreate.js' %}"></script>


  <script>
   

  </script>
</body>

</html>

Tktapp/templates/test.html
{% load static %}
<form action="" method="POST">
{% csrf_token %}
{{ form.as_p}}
<input type="submit">
</form>